#! /bin/bash

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &
~/.config/bspwm/polybar/launch.sh &
pgrep -x dunst > /dev/null || dunst -config $HOME/.config/bspwm/dunstrc &
pgrep -x picom > /dev/null || picom --config $HOME/.config/bspwm/picom.conf &

xrandr --output DP-4 --off --mode 2560x1440

# ~/.fehbg &

/usr/libexec/polkit-gnome-authentication-agent-1 &
#deckmaster -deck ~/.config/deck/main.deck &
[ ! -s ~/.config/mpd/pid ] && mpd &
clipmenud &

bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap           10
bspc config split_ratio          0.5
bspc config focus_follows_pointer true
bspc config presel_feedback_color "#d4be98"

bspc rule -a mysp state=floating rectangle=1280x800+380+170
bspc rule -a scp2 state=floating rectangle=1280x800+380+170
bspc rule -a pulse state=floating rectangle=1280x800+380+170
bspc rule -a music state=floating rectangle=1280x800+380+170
bspc rule -a news state=floating rectangle=1280x800+380+170
bspc rule -a ranger state=floating rectangle=1280x800+380+170
# Theme concept from https://github.com/Sinomor/dots/tree/main
#
