#!/bin/bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_shadow              float        \
                window_opacity             off          \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.5          \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                5            \
                bottom_padding             5            \
                left_padding               5            \
                right_padding              5            \
                window_gap                 5

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(System Settings|Dictionary|Photo Booth|Archive Utility|Calculator)$" manage=off
yabai -m rule --add app="^(VLC|IINA|Karabiner-Elements|LinearMouse)$" manage=off

yabai -m config layout bsp
