#!/bin/bash

# Remove existing signals (in case of restart)
yabai -m signal --remove "sketchybar_space_change" 2>/dev/null
yabai -m signal --remove "sketchybar_front_app" 2>/dev/null

yabai -m signal --add event=space_changed action="sketchybar --trigger space_change" label="sketchybar_space_change"
yabai -m signal --add event=window_focused action="sketchybar --trigger front_app_switched" label="sketchybar_front_app"
y
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config external_bar               all:32:0     \
                window_border              on           \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             off          \
                window_opacity_duration    0.0          \
                active_window_opacity      1.0          \
                normal_window_opacity      0.0          \
                window_border_width        2            \
                window_border_hidpi        off          \
                window_border_radius       11           \
                window_border_blur         off          \
                window_animation_duration  0            \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff494d64   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                8            \
                bottom_padding             8            \
                left_padding               8            \
                right_padding              8            \
                window_gap                 8

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(System Settings|Dictionary|Photo Booth|Archive Utility|Calculator)$" manage=off
yabai -m rule --add app="^(VLC|IINA|Karabiner-Elements|LinearMouse)$" manage=off

yabai -m config layout bsp

# Assign apps to specific workspace
#yabai -m rule --add app="^([Ss]afari|[Ff]irefox|[Ll]ibreWolf|[Zz]en|Brave Browser|Google Chrome|[Qq]utebrowser)$" space=2
yabai -m rule --add app="^([Dd]iscord|[Vv]esktop|[Ss]ignal)$" space=4
yabai -m rule --add app="^[Ss]team Helper$" space=5
yabai -m rule --add app="^OBS Studio$" space=6
